n1 = int(input('Digite um valor: '))
n2 = int(input('Digite outro valor: '))
s = n1+n2
su = n1-n2
m = n1*n2
d = n1/n2
p = n1**n2
di = n1//n2
print('A soma é {}, a subtração é {}, a multiplicação é {}, a divisão é {:.2f}, \n a potência é {} e a divisão inteira é {}'.format(s,su,m,d,p,di), end='>>')