frase = str(input('Digite uma frase:')).lower().strip()
print('A frase é: {}'.format(frase))
print('A letra "a" aparece {} vezes...'.format(frase.count('a')))
print('A primeira letra "a" aparece na posição {}'.format(frase.find('a')+1))
print('A ultima letra "a" aparece na posição {}'.format(frase.rfind('a')+1))
